language: node_js
node_js:
- "stable"

addons:
  ssh_known_hosts:
    - 120.50.78.185

before_install:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - ls -al .travis

before_script:
  cd Back-End && npm install

after_success:
  - npm run coveralls
  - git remote add production ssh://fonnie@120.50.78.185/CustomBlog
  - git push production deploy 

# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: bash deploy.sh
#     on:
#       branch: deploy