language: node_js
node_js:
- "stable"

before_script:
  cd Back-End && npm install && chmod +x json.sh

after_success:
  - npm run coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: "echo '{\"key\":\"$deploy_key\"}' > key.json && cat key.json && curl --data @key.json -H \"Content-Type: application/json\" -X POST http://120.50.78.185:3200/deploy"
    on:
      branch: deploy