language: node_js
node_js:
- "stable"

before_script:
  cd Back-End && npm install

after_success:
  - npm run coveralls
  - curl -d '{"key": $deploy_key}' -H "Content-Type: application/json" -X POST http://120.50.78.185:3200/deploy