language: node_js
node_js:
- "stable"

before_script:
  cd Back-End && npm install

after_success:
  - npm run coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: "curl -X POST --data '{\"key\": $deploy_key}' -H \"Content-Type: application/json\" http://120.50.78.185:3200/deploy"
    on:
      branch: deploy
