language: node_js
node_js:
- "stable"

before_script:
  cd Back-End && npm install

after_success:
  - npm run coveralls
  - echo "$ftp_pk" | base64 --decode >/tmp/sftp_rsa
  - cat /tmp/sftp_rsa
  - find ./ -exec curl -u "$ftp_user":"$ftp_pw" -T {} ftp://120.50.78.185/CustomBlog/Bak-End/ \;